### ISSUE TITLE
Demo scene not found

### ISSUE THREAD

**Issue by stephan000** [CBI777/Realtime_SMPLX_with_Unity#1]
### Description

Thank you for sharing the code.

I could not find the demo scene `./RealTimeSMPL/Scene/RealTimeSMPLX`.
Could you please share it?

**Comment by CBI777** [comment]
Hello, Stephan.

I've made some changes and commits, including missing demo scene.
Hope it helps, cheers.

**Comment by stephan000** [comment]
The demo has worked correctly. Thanks!
